### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by zhaoc1** [metasnv-tool/metaSNV#2]
Hi,

I installed metaSNV via conda and ran `metaSNV.py` for five samples.

```
metaSNV.py --threads 4 output_default list_of_bam /path/to/bwa_index.fa
```

And I encountered an error message:
```
munmap_chunk(): invalid pointer

Failure in sample XXX.bamCall to /home/ubuntu/miniconda3/envs/metaSNV/share/metasnv-2.0.1/src/qaTools/qaCompute -c 10 -d -i XXX.bam output_default/cov/XXX.bam.cov failed
```

I don't really have enough information to debug this error, so I ran the failed command printed by metaSNV, and got a bit more information about the error:

```
Probably really good coverage, since variables overrun!
That's a big sum: 867000...
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

Any clues what's going on here? Thank you!

Chunyu

**Comment by LucasPaoli** [comment]
Hi Chunyu,

Right, so, that doesn't look great. After some digging into qaCompute, it looks like the total coverage may be breaking the integer limit.

Do you have an idea of the genome size(s) and coverage in the samples? If this is what I suspect, the only option I see is to subsample the reads before generating the bamfiles or directly subsampling the bamfiles.

Lucas
