### ISSUE TITLE
indels

### ISSUE THREAD

**Issue by alimayy** [metasnv-tool/metaSNV#4]
Does metaSNP's snpCall call indels by default? If not, is there something I can do to enable indel calls?

**Comment by LucasPaoli** [comment]
Dear Ali,

Thank you for using metaSNV. Unfortunately metaSNV was never intended for indel calling so I wouldn't recommend it for that purpose.

Several tools out there should help you with that. For instance, I think Anvio can now profile indels: https://merenlab.org/software/anvio/help/7/artifacts/variability-profile/

Best,

Lucas
